# Generated by Django 6.0.7 on 2026-08-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_increment',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
